### ISSUE TITLE
Pieces not shown on PgnViewer examples site

### ISSUE THREAD

**Issue by Bebul** [mliebelt/PgnViewerJS#180]
Examples from your site does not show pieces on chessboard, at least when opened on android chrome.

https://mliebelt.github.io/PgnViewerJS/examples.html#1000

![Screenshot_20201108-162918_Chrome](https://user-images.githubusercontent.com/9265147/98469666-40981900-21e1-11eb-9af2-cab042b51294.jpg)

**Comment by mliebelt** [comment]
Thank you for bringing this to my notice. Any idea how to find the reason for it? There is of course no source code written by myself, that hinders Chrome on Android to display it correctly. I have checked it with Chrome (current) under Linux (my host computer), and had no problem. It works as well with Firefox, Vivaldi, internal browser on Android phone, all work well.

Any idea how to debug it? I have no clue, and I don't see any "development tools" in Android Chrome that may help to find the reason for the failure. Interestingly, when I use Google Chrome the incognito tab, the viewer works. 

So I understand that this may be a problem for you, but I will not invest time here without any hint how to diagnose or solve the problem. Perhaps Google should fix their browser?

**Comment by Bebul** [comment]
Thank you for response. I am about to try some tests with it later. So I will give it some time. And we will see.

**Comment by Bebul** [comment]
@mliebelt Seems I have something, I was able to run chrome developers tools while connected through USB and I have found the following:

Full path to original svg image works:
```css
.merida cg-board piece.knight.black {
    background-image: url(https://mliebelt.github.io/PgnViewerJS/js/pgnv-assets/46c4b3a….svg);
}
```
![image](https://user-images.githubusercontent.com/9265147/98542299-f8d0ca80-2290-11eb-98f0-cc398269e49e.png)

I have tried to change the black rook to some other picture before.

**Comment by Bebul** [comment]
Huh, this one, relative, works too:
```css
.merida cg-board piece.bishop.black {
    background-image: url(js/pgnv-assets/e1a52ad….svg);
}
```
![image](https://user-images.githubusercontent.com/9265147/98542759-acd25580-2291-11eb-8038-fe0522061111.png)
